# Generated by Django 3.2.7 on 2021-11-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribed_services_notification',
            field=models.ManyToManyField(to='service_catalog.Service'),
        ),
    ]
