# Generated by Django 3.2.13 on 2022-08-04 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_auto_20220718_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotabinding',
            name='red_threshold_percent',
            field=models.IntegerField(blank=True, default=90, help_text='Threshold at which the color changes to red. Threshold is reverse when the red threshold is lower than the yellow threshold.', verbose_name='Red threshold percent consumed'),
        ),
        migrations.AddField(
            model_name='quotabinding',
            name='yellow_threshold_percent',
            field=models.IntegerField(blank=True, default=80, help_text='Threshold at which the color changes to yellow. Threshold is reverse when the red threshold is lower than the yellow threshold.', verbose_name='Yellow threshold percent consumed'),
        ),
        migrations.AlterField(
            model_name='billinggroup',
            name='user_set',
            field=models.ManyToManyField(blank=True, help_text='The users in this billing group.', related_name='billing_groups', related_query_name='billing_groups', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
