# Generated by Django 3.2.13 on 2022-10-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20220804_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationfilter',
            name='instance_states',
        ),
        migrations.AlterField(
            model_name='notificationfilter',
            name='when',
            field=models.TextField(blank=True, help_text="Ansible like 'when' with `request` as context. No Jinja brackets needed", null=True),
        ),
    ]
