# Generated by Django 3.2.13 on 2023-06-07 08:38

from django.db import migrations


def clean_quota(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentType.objects.filter(app_label="profiles", model='quota').delete()
    ContentType.objects.filter(app_label="profiles", model='quotabinding').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_clean_role_bindings'),
    ]
    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS profiles_quota_attribute_definitions"),
        migrations.AlterUniqueTogether(
            name='quotabinding',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quotabinding',
            name='billing_group',
        ),
        migrations.RemoveField(
            model_name='quotabinding',
            name='quota',
        ),
        migrations.DeleteModel(
            name='Quota',
        ),
        migrations.DeleteModel(
            name='QuotaBinding',
        ),
        migrations.RunSQL("DELETE FROM auth_permission WHERE content_type_id in (SELECT id FROM django_content_type WHERE model = 'quota');"),
        migrations.RunSQL("DELETE FROM auth_permission WHERE content_type_id in (SELECT id FROM django_content_type WHERE model = 'quotabinding');"),
        migrations.RunSQL("DELETE FROM django_content_type WHERE app_label = 'profiles' AND model = 'quota';"),
        migrations.RunSQL("DELETE FROM django_content_type WHERE app_label = 'profiles' AND model = 'quotabinding';"),
    ]
