# Generated by Django 3.2.13 on 2023-06-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0013_auto_20230622_1404'),
        ('profiles', '0010_clean_quota'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamrolebinding',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teamrolebinding',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='teamrolebinding',
            name='role',
        ),
        migrations.RemoveField(
            model_name='teamrolebinding',
            name='team',
        ),
        migrations.AlterUniqueTogether(
            name='userrolebinding',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrolebinding',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userrolebinding',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrolebinding',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamRoleBinding',
        ),
        migrations.DeleteModel(
            name='UserRoleBinding',
        ),
    ]
