# Generated by Django 3.2.13 on 2023-06-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0015_remove_instance_billing_group'),
        ('profiles', '0012_auto_20230622_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingGroup',
        ),
    ]
