# Generated by Django 3.2.13 on 2023-06-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='dark', max_length=20),
        ),
    ]
