# Generated by Django 3.2.13 on 2023-07-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker_v2', '0004_alter_transformer_factor'),
        ('profiles', '0016_auto_20230724_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='attribute_definition',
            field=models.ForeignKey(help_text='The attribute definitions linked to this quota.', on_delete=django.db.models.deletion.CASCADE, related_name='quotas', related_query_name='quota', to='resource_tracker_v2.attributedefinition', verbose_name='Attribute'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='scope',
            field=models.ForeignKey(help_text='The attribute definitions linked to this quota.', on_delete=django.db.models.deletion.CASCADE, related_name='quotas', related_query_name='quota', to='profiles.scope', verbose_name='Scope'),
        ),
    ]
