# Generated by Django 3.2.13 on 2023-07-31 14:34

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profiles', '0017_auto_20230724_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': ('add', 'change', 'delete', 'view', 'list'),
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.permission', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.AlterField(
            model_name='globalpermission',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions assigned to all users without exception.', limit_choices_to={'content_type__app_label__in': ['service_catalog', 'profiles', 'resource_tracker_v2', 'auth']}, to='profiles.Permission'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions linked to this role.', limit_choices_to={'content_type__app_label__in': ['service_catalog', 'profiles', 'resource_tracker_v2', 'auth']}, to='profiles.Permission'),
        ),
    ]
