# Generated by Django 3.2.13 on 2023-09-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20230803_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quota',
            options={'default_permissions': ('add', 'delete', 'view', 'list'), 'permissions': [('change_team_quota', 'Can change quota at team level'), ('change_organization_quota', 'Can change quota at organization level')]},
        ),
    ]
