# Generated by Django 3.2.13 on 2023-09-28 13:13

from django.db import migrations, models

def rename_globalpermission_to_globalscope(apps, schema_editor):
    GlobalPermission = apps.get_model('profiles', 'GlobalPermission')
    GlobalPermission.objects.filter(name="GlobalPermission").update(name="GlobalScope")

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_quota_options'),
    ]

    operations = [
        migrations.RunPython(rename_globalpermission_to_globalscope),
        migrations.AddField(
            model_name='globalpermission',
            name='owner_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions assigned to the owner of Squest objects.',
                                         limit_choices_to={'content_type__model__in': ['instance', 'request', 'support',
                                                                                       'supportmessage',
                                                                                       'requestmessage',
                                                                                       'approvalstep']},
                                         related_name='ownerpermission', related_query_name='ownerpermission',
                                         to='profiles.Permission'),
        ),
        migrations.AlterField(
            model_name='globalpermission',
            name='default_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions assigned to all users without exception.',
                                         limit_choices_to={
                                             'content_type__app_label__in': ['service_catalog', 'profiles',
                                                                             'resource_tracker_v2', 'auth']},
                                         related_name='globalpermission', related_query_name='globalpermission',
                                         to='profiles.Permission'),
        ),
        migrations.RenameModel(
            old_name='GlobalPermission',
            new_name='GlobalScope',
        ),
        migrations.AlterModelOptions(
            name='globalscope',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list'),
                     'permissions': [('view_users_globalscope', 'Can view users in global scope'),
                                     ('add_users_globalscope', 'Can add users in global scope'),
                                     ('delete_users_globalscope', 'Can delete users in global scope')]},
        ),
        migrations.RenameField(
            model_name='globalscope',
            old_name='default_permissions',
            new_name='global_permissions',
        ),
    ]
