# Generated by Django 3.2.13 on 2023-10-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_create_default_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list'), 'ordering': ['content_type__model', 'codename']},
        ),
    ]
