# Generated by Django 4.2.6 on 2023-11-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_alter_permission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quota',
            options={'default_permissions': ('add', 'delete', 'view', 'list'), 'ordering': ('attribute_definition__attribute_group__name', 'attribute_definition__name'), 'permissions': [('change_team_quota', 'Can change quota at team level'), ('change_organization_quota', 'Can change quota at organization level')]},
        ),
    ]
