# Generated by Django 3.1.7 on 2021-03-09 09:26

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TowerServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=200, unique=True)),
                ('token', models.CharField(max_length=200)),
                ('secure', models.BooleanField(default=True)),
                ('ssl_verify', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tower_id', models.IntegerField()),
                ('survey', jsonfield.fields.JSONField()),
                ('tower_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_catalog.towerserver')),
            ],
        ),
    ]
