# Generated by Django 3.1.7 on 2021-03-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towerserver',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
