# Generated by Django 3.1.7 on 2021-03-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0002_auto_20210308_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='towerserver',
            old_name='url',
            new_name='host',
        ),
    ]
