# Generated by Django 3.1.7 on 2021-03-08 17:43

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0003_auto_20210308_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tower_id', models.IntegerField()),
                ('survey', jsonfield.fields.JSONField()),
            ],
        ),
    ]
