- name: Add resource in resource group example
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    squest_api: "http://127.0.0.1:8000/api/"
    resource_group_name: "OCP Worker node"
    squest: # this would be the sent data from squest as extra vars
      request:
        instance:
          id: 8
          name: test
          service: 1
          spec: { }
          state: PROVISIONING
    vm_name: "test-vm"
    vm_vcpu: 4
    vm_memory: 16
    desc: "My description"
    squest_token: 48c67f9c2429f2d3a1ee0e47daa00ffeef4fe744

  tasks:
    - name: Print info sent by Squest
      debug:
        var: squest

    # -----------------------
    # PLACE HERE ALL THE MAGIC TO CREATE THE RESOURCE
    # -----------------------
    - name: Get resource group id
      uri:
        url: "{{ squest_api }}resource_tracker/resource_group/"
        headers:
          Authorization: "Token {{ squest_token }}"
        method: GET
        status_code: 200
        body_format: json
      register: output

    - name: Setting host facts using complex arguments
      set_fact:
        resource_group_vm_id: "{{ output.json | selectattr('name', 'equalto', resource_group_name ) | map(attribute='id') | list | first  }}"

    - name: Create a resource in squest
      uri:
        url: "{{ squest_api }}resource_tracker/resource_group/{{ resource_group_vm_id }}/resources/"
        headers:
          Authorization: "Token {{ squest_token }}"
        method: POST
        body:
          name: "{{ vm_name }}"
          service_catalog_instance: "{{ squest['request']['instance']['id'] }}"
          attributes:
            - name: "vCPU"
              value: "{{ vm_vcpu }}"
            - name: "Memory"
              value: "{{ vm_memory }}"
          text_attributes:
            - name: "Comments"
              value: "{{ desc }}"
        status_code: 201
        body_format: json