# ansible-playbook playbook_examples/test_get_api.yml \
# -i playbook_examples/squest_inventory/inventory

---
- name: Get info from squest API
  hosts: squest_testing
  gather_facts: false

  tasks:
    - name: Get all resource group
      uri:
        url: "{{ squest_api }}resource_tracker/resource_group/"
        headers:
          Authorization: Token {{ squest_token }}
        method: GET
        status_code: 200
        body_format: json
      register: output

    - debug:
        var: output
