# docker-compose -f dev-env.docker-compose.yml up
version: '3.7'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: squest_db
      MYSQL_USER: squest_user
      MYSQL_PASSWORD: squest_password
      MYSQL_ROOT_PASSWORD: p@ssw0rd
    volumes:
      - db_data:/var/lib/mysql
      - "${PWD}/docker/scripts/mariadb-init.sql:/docker-entrypoint-initdb.d/mariadb-init.sql"
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: p@ssw0rd
    ports:
      - "8082:80"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "squest"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  db_data: {}
  rabbitmq_data: {}
