# add this file to the docker compose execution when developing Squest
services:

  db:
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    env_file: docker/environment_variables/phpmyadmin.env
    ports:
      - "8082:80"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  redis-cache:
    ports:
      - "6379:6379"
