# docker-compose -f docker-compose.yml up
services:

  db:
    image: mariadb:11.0.2
    env_file: docker/environment_variables/db.env
    volumes:
      - db_data:/var/lib/mysql
      - "./docker/scripts/mariadb-init.sh:/docker-entrypoint-initdb.d/db-init.sh"

  rabbitmq:
    image: rabbitmq:3.13.2-management
    env_file: docker/environment_variables/rabbitmq.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis-cache:
    image: redis:6.2.13-alpine
    command:
    - sh
    - -c
    - redis-server --maxmemory-policy allkeys-lru --requirepass $$REDIS_PASSWORD  ## $$ because of docker-compose
    env_file: docker/environment_variables/redis.env

  django: &django
    image: ${SQUEST_IMAGE:-quay.io/hewlettpackardenterprise/squest}:${SQUEST_TAG:-latest}
    env_file: docker/environment_variables/squest.env
    volumes:
      - django_static:/app/static
      - django_media:/app/media
      - backup:/app/backup
      - ./plugins:/app/plugins
    depends_on:
      - db
      - rabbitmq
      - celery-worker
      - celery-beat
      - redis-cache

  nginx:
    command: nginx -c /etc/nginx/squest/nginx.conf
    image: nginx:1.23.4-alpine
    depends_on:
      - django
    volumes:
      - django_media:/app/media:ro
      - django_static:/app/static:ro
      - ./docker/nginx.conf:/etc/nginx/squest/nginx.conf:ro

  maintenance:
    image: nginx:1.23.4-alpine
    volumes:
      - ./docker/maintenance.html:/usr/share/nginx/html/index.html
      - ./docker/maintenance.nginx.conf:/etc/nginx/conf.d/default.conf
      - ./project-static/squest/img/squest_logo_v2_300_300.png:/usr/share/nginx/html/squest_logo_v2_300_300.png

  celery-worker:
    <<: *django
    env_file:
      - docker/environment_variables/squest.env
      - docker/environment_variables/celery.env
    depends_on:
      - db
      - rabbitmq
    ports: []
    command: >
      bash -c "/wait &&
      celery -A service_catalog worker -l info"

  celery-beat:
    <<: *django
    env_file:
      - docker/environment_variables/squest.env
      - docker/environment_variables/celery.env
    depends_on:
      - db
      - rabbitmq
    ports: []
    command: >
      bash -c "/wait &&
      celery -A service_catalog beat -l info"

volumes:
  db_data: {}
  rabbitmq_data: {}
  django_static: {}
  django_media: {}
  backup: {}
