services:
  django:
    image: quay.io/hewlettpackardenterprise/squest:2.8.1
    volumes:
      - django_static:/app/static
      - django_media:/app/media
      - backup:/app/backup
      - ./plugins:/app/plugins
      # Mount local code to test password fix
      - ./service_catalog:/app/service_catalog
      # Mount templates to test password masking
      - ./templates:/app/templates
    environment:
      - DEBUG=True

  celery-worker:
    image: quay.io/hewlettpackardenterprise/squest:2.8.1
    volumes:
      - django_media:/app/media
      - backup:/app/backup
      - ./plugins:/app/plugins
      # Mount local code to test password fix
      - ./service_catalog:/app/service_catalog
    environment:
      - DEBUG=True

  celery-beat:
    image: quay.io/hewlettpackardenterprise/squest:2.8.1
    volumes:
      - django_media:/app/media
      - backup:/app/backup
      - ./plugins:/app/plugins
      # Mount local code to test password fix
      - ./service_catalog:/app/service_catalog
    environment:
      - DEBUG=True

  nginx:
    ports:
      - "8080:80"