# docker-compose -f docker-compose.yml up
version: '3.7'

services:
  db:
    image: mariadb:latest
    env_file: docker/environment_variables/db.env
    volumes:
      - db_data:/var/lib/mysql
      - "./docker/scripts/mariadb-init.sql:/docker-entrypoint-initdb.d/mariadb-init.sql"
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    env_file: docker/environment_variables/phpmyadmin.env
    ports:
      - "8082:80"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    env_file: docker/environment_variables/rabbitmq.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  django: &django
    image: squest
    build:
      context: .
      dockerfile: docker/squest.Dockerfile
    env_file: docker/environment_variables/squest.env
    volumes:
      - django_static:/app/static
      - django_media:/app/media
      - backup:/app/backup
    depends_on:
      - db
      - rabbitmq
      - celery-worker
      - celery-beat

  nginx:
    command: nginx -c /etc/nginx/squest/nginx.conf
    image: nginx:alpine
    depends_on:
      - django
    volumes:
      - django_media:/app/media:ro
      - django_static:/app/static:ro
      - ./docker/nginx.conf:/etc/nginx/squest/nginx.conf:ro

  celery-worker:
    <<: *django
    depends_on:
      - db
      - rabbitmq
    ports: []
    command: >
      bash -c "/wait &&
      celery -A service_catalog worker -l info"

  celery-beat:
    <<: *django
    depends_on:
      - db
      - rabbitmq
    ports: []
    command: >
      bash -c "/wait &&
      celery -A service_catalog worker --beat -l info"

volumes:
  db_data: {}
  rabbitmq_data: {}
  django_static: {}
  django_media: {}
  backup: {}
