services:
  django:
    volumes:
      - django_static:/app/static
      - django_media:/app/media
      - backup:/app/backup
      - ./plugins:/app/plugins
      # Mount local code to test password fix
      - ./service_catalog:/app/service_catalog
    environment:
      - DEBUG=True

  celery-worker:
    volumes:
      - django_media:/app/media
      - backup:/app/backup
      - ./plugins:/app/plugins
      # Mount local code to test password fix
      - ./service_catalog:/app/service_catalog
    environment:
      - DEBUG=True

  celery-beat:
    volumes:
      - django_media:/app/media
      - backup:/app/backup
      - ./plugins:/app/plugins
      # Mount local code to test password fix
      - ./service_catalog:/app/service_catalog
    environment:
      - DEBUG=True