# docker-compose -f docker-compose.yml up
version: '3.7'

services:

  db:
    image: mariadb:latest
    env_file: docker/environment_variables/db.env
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - "./docker/scripts/mariadb-init.sh:/docker-entrypoint-initdb.d/db-init.sh"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    env_file: docker/environment_variables/phpmyadmin.env
    ports:
      - "8082:80"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    env_file: docker/environment_variables/rabbitmq.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis-cache:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    command:
    - sh
    - -c
    - redis-server --maxmemory-policy allkeys-lru --requirepass $$REDIS_PASSWORD  ## $$ because of docker-compose
    env_file: docker/environment_variables/redis.env

  django: &django
    image: quay.io/hewlettpackardenterprise/squest:latest
    env_file: docker/environment_variables/squest.env
    volumes:
      - django_static:/app/static
      - django_media:/app/media
      - backup:/app/backup
      - ./plugins/field_validators:/app/plugins/field_validators
    depends_on:
      - db
      - rabbitmq
      - celery-worker
      - celery-beat
      - redis-cache

  nginx:
    command: nginx -c /etc/nginx/squest/nginx.conf
    image: nginx:alpine
    depends_on:
      - django
    volumes:
      - django_media:/app/media:ro
      - django_static:/app/static:ro
      - ./docker/nginx.conf:/etc/nginx/squest/nginx.conf:ro

  maintenance:
    image: nginx:alpine
    volumes:
      - ./docker/maintenance.html:/usr/share/nginx/html/index.html
      - ./docker/maintenance.nginx.conf:/etc/nginx/conf.d/default.conf
      - ./project-static/squest/img/squest_full_logo_transparent.png:/usr/share/nginx/html/squest_full_logo_transparent.png

  celery-worker:
    <<: *django
    env_file:
      - docker/environment_variables/squest.env
      - docker/environment_variables/celery.env
    depends_on:
      - db
      - rabbitmq
    ports: []
    command: >
      bash -c "/wait &&
      celery -A service_catalog worker -l info"

  celery-beat:
    <<: *django
    env_file:
      - docker/environment_variables/squest.env
      - docker/environment_variables/celery.env
    depends_on:
      - db
      - rabbitmq
    ports: []
    command: >
      bash -c "/wait &&
      celery -A service_catalog worker --beat -l info"

volumes:
  db_data: {}
  rabbitmq_data: {}
  django_static: {}
  django_media: {}
  backup: {}
