# docker-compose -f docker-compose.yml up
version: '3.7'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: squest_db
      MYSQL_USER: squest_user
      MYSQL_PASSWORD: squest_password
      MYSQL_ROOT_PASSWORD: p@ssw0rd
    volumes:
      - db_data:/var/lib/mysql
      - "${PWD}/docker/scripts/mariadb-init.sql:/docker-entrypoint-initdb.d/mariadb-init.sql"
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: p@ssw0rd
    ports:
      - "8082:80"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "squest"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  django: &django
    image: squest
    build:
      context: .
      dockerfile: docker/squest.Dockerfile
    environment:
      MYSQL_SERVICE_HOST: db
      WAIT_HOSTS: db:3306, rabbitmq:5672
      CELERY_BROKER_URL: amqp://rabbitmq:rabbitmq@rabbitmq:5672/squest
      SQUEST_ENV: production
    volumes:
      - django_static:/app/static
      - django_media:/app/media
    depends_on:
      - db
      - rabbitmq
      - celery-worker
      - celery-beat

  nginx:
    command: nginx -c /etc/nginx/squest/nginx.conf
    image: nginx:alpine
    depends_on:
      - django
    volumes:
      - django_media:/app/media:ro
      - django_static:/app/static:ro
      - ./docker/nginx.conf:/etc/nginx/squest/nginx.conf:ro

  celery-worker:
    <<: *django
    depends_on:
      - db
      - rabbitmq
    ports: []
    command: >
      bash -c "/wait &&
      celery -A service_catalog worker -l info"

  celery-beat:
    <<: *django
    depends_on:
      - db
      - rabbitmq
    ports: []
    command: >
      bash -c "/wait &&
      celery -A service_catalog worker --beat --scheduler django -l info"

volumes:
  db_data: {}
  rabbitmq_data: {}
  django_static: {}
  django_media: {}
