# docker-compose -f dev-env.docker-compose.yml -f full-env.docker-compose.yml up
version: '3.7'

services:
  django: &django
    image: squest
    build:
      context: .
      dockerfile: docker/squest.Dockerfile
    environment:
      MYSQL_SERVICE_HOST: db
      WAIT_HOSTS: db:3306, rabbitmq:5672
      CELERY_BROKER_URL: amqp://rabbitmq:rabbitmq@rabbitmq:5672/squest
      SQUEST_ENV: production
    volumes:
      - django_static:/app/static
      - django_media:/app/media
    depends_on:
      - db
      - rabbitmq
      - celery-worker
      - celery-beat

  nginx:
    command: nginx -c /etc/nginx/squest/nginx.conf
    image: nginx:alpine
    depends_on:
      - django
    ports:
      - "8080:8080"
    volumes:
      - django_media:/app/media:ro
      - django_static:/app/static:ro
      - ./docker/nginx.conf:/etc/nginx/squest/nginx.conf:ro

  celery-worker:
    <<: *django
    depends_on:
      - db
      - rabbitmq
    ports: []
    command: >
      bash -c "/wait &&
      celery -A service_catalog worker -l info"

  celery-beat:
    <<: *django
    depends_on:
      - db
      - rabbitmq
    ports: []
    command: >
      bash -c "/wait &&
      celery -A service_catalog worker --beat --scheduler django -l info"

volumes:
  django_static: {}
  django_media: {}
