site_name: Squest
repo_name: HewlettPackard/squest
repo_url: https://github.com/HewlettPackard/squest

theme:
  name: material
  palette:
    scheme: default
    primary: green
    accent: deep orange
  logo: images/squest_logo_white.png

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.9.2/mermaid.min.js

extra:
  version:
    provider: mike

markdown_extensions:
  - pymdownx.highlight
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

nav:
  - Home: index.md
  - Installation:
    - LDAP: installation/ldap.md
    - TLS: installation/tls.md
    - Backup: installation/backup.md
    - Upgrade: installation/upgrade.md
  - Configuration:
    - Squest: configuration/squest_settings.md
    - Tower: configuration/tower_settings.md
  - Manual:
    - Service catalog:
      - Concept: manual/service_catalog/concept.md
      - Service: manual/service_catalog/service.md
      - Operation: manual/service_catalog/operation.md
    - Resource tracking: manual/resource_tracking.md
    - Tools: manual/tools.md
    - Quota: manual/quota.md
    - Teams: manual/teams.md
    - REST API: manual/api.md
    - Prometheus metrics: manual/metrics.md
    - Notifications: manual/notifications.md
    - Filters: manual/filters.md
    - Jinja: manual/jinja.md
  - Development:
    - Setup a dev env: dev/dev-env.md
    - Request state machine: dev/request-state-machine.md
    - Instance state machine: dev/instance-state-machine.md
    - Database ERD: dev/db-erd.md
    - Plugins:
      - Field validator:  dev/plugins/validators.md
  - Contribute:
      - Code: contribute/code.md
      - Documentation: contribute/documentation.md
