site_name: Squest
repo_name: HewlettPackard/squest
repo_url: https://github.com/HewlettPackard/squest

theme:
  name: material
  palette:
    scheme: default
    primary: green
    accent: deep orange
  logo: images/squest_logo_white.png

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.9.2/mermaid.min.js

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

nav:
  - Home: index.md
  - Deployment: deployment.md
  - Configuration:
    - Squest: squest_settings.md
    - Tower: tower_settings.md
  - Manual:
    - Service catalog: manual/service_catalog.md
    - Resource tracking: manual/resource_tracking.md
    - Settings: manual/settings.md
  - Development:
    - Setup a dev env: dev/dev-env.md
    - Request state machine: dev/request-state-machine.md
    - Instance state machine: dev/instance-state-machine.md
    - Database ERD: dev/db-erd.md
  - Contribute:
      - Code: contribute/code.md
      - Documentation: contribute/documentation.md
