site_name: Squest
repo_name: HewlettPackard/squest
repo_url: https://github.com/HewlettPackard/squest

theme:
  name: material
  palette:
    scheme: default
    primary: green
    accent: deep orange
  logo: images/squest_logo_white.png

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.9.2/mermaid.min.js

extra:
  version:
    provider: mike

markdown_extensions:
  - pymdownx.highlight
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Configuration:
    - Squest: configuration/squest_settings.md
    - LDAP: configuration/ldap.md
    - TLS: configuration/tls.md
  - Manual:
    - Service catalog:
      - Concept: manual/service_catalog/concept.md
      - Service: manual/service_catalog/service.md
      - Operation: manual/service_catalog/operation.md
      - Survey: manual/service_catalog/survey.md
    - Resource tracking:
      - Concept: manual/resource_tracking/concept.md
      - Attribute: manual/resource_tracking/attributes.md
      - Resource group: manual/resource_tracking/resource_group.md
      - Resource: manual/resource_tracking/resource.md
    - Access: manual/access.md
    - Administration:
        - RHAAP/AWX: manual/administration/rhaap.md
        - Approval workflow: manual/administration/approval_workflow.md
        - RBAC: manual/administration/rbac.md
        - Extras: manual/administration/extras.md
    - Advanced:
        - manual/advanced/filters.md
        - manual/advanced/jinja.md
        - manual/advanced/validators.md
    - Notifications: manual/notifications.md
  - Administration:
      - Backup: administration/backup.md
      - Upgrade: administration/upgrade.md
      - REST API: administration/api.md
      - Prometheus metrics: administration/metrics.md
  - Development:
    - Setup a dev env: dev/dev-env.md
    - Request state machine: dev/request-state-machine.md
    - Instance state machine: dev/instance-state-machine.md
    - Release: dev/release.md
  - Contribute:
      - Code: contribute/code.md
      - Documentation: contribute/documentation.md
  - Release notes: release_notes.md
