services:
  db:
    image: mariadb:latest
    env_file: docker/environment_variables/mysql.env
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - "./docker/scripts/mariadb-init.sh:/docker-entrypoint-initdb.d/mariadb-init.sh"

  django:
    environment:
      WAIT_HOSTS: db:3306,rabbitmq:5672

  celery-worker:
    environment:
      WAIT_HOSTS: db:3306,rabbitmq:5672,django:8000
      WAIT_TIMEOUT: 60

  celery-beat:
    environment:
      WAIT_HOSTS: db:3306,rabbitmq:5672,django:8000
      WAIT_TIMEOUT: 60