
services:
  db:
    image: postgres:latest
    env_file: docker/environment_variables/db.env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - "./docker/scripts/psql-init.sh:/docker-entrypoint-initdb.d/db-init.sh"

  django:
    environment:
      WAIT_HOSTS: db:5432,rabbitmq:5672

  celery-worker:
    environment:
      WAIT_HOSTS: db:5432,rabbitmq:5672,django:8000
      WAIT_TIMEOUT: 60

  celery-beat:
    environment:
      WAIT_HOSTS: db:5432,rabbitmq:5672,django:8000
      WAIT_TIMEOUT: 60