from django.db.models import IntegerChoices


class InstanceState(IntegerChoices):
    PENDING = 1, "PENDING"
    PROVISION_FAILED = 2, "PROVISION_FAILED"
    PROVISIONING = 3, "PROVISIONING"
    UPDATING = 4, "UPDATING"
    UPDATE_FAILED = 5, "UPDATE_FAILED"
    DELETING = 6, "DELETING"
    DELETED = 7, "DELETED"
    DELETE_FAILED = 8, "DELETE_FAILED"
    ARCHIVED = 9, "ARCHIVED"
    AVAILABLE = 10, "AVAILABLE"
    ABORTED = 11, "ABORTED"
