# Generated by Django 3.2.13 on 2023-06-02 09:02
from django.db import migrations


def clean_resource_v1(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentType.objects.filter(app_label="resource_tracker").delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('service_catalog', '0012_auto_20221004_1808'),
        ('profiles', '0010_clean_quota'),
    ]
    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS resource_tracker_resourceattribute"),
        migrations.RunSQL("DROP TABLE IF EXISTS resource_tracker_resourcetextattribute"),
        migrations.RunSQL("DROP TABLE IF EXISTS resource_tracker_resourcegrouptextattributedefinition"),
        migrations.RunSQL("DROP TABLE IF EXISTS resource_tracker_resourcegroupattributedefinition"),
        migrations.RunSQL("DROP TABLE IF EXISTS resource_tracker_resourcepoolattributedefinition"),
        migrations.RunSQL("DROP TABLE IF EXISTS resource_tracker_resource"),
        migrations.RunSQL("DROP TABLE IF EXISTS resource_tracker_resourcegroup"),
        migrations.RunSQL("DROP TABLE IF EXISTS resource_tracker_resourcepool"),
        migrations.RunPython(clean_resource_v1),
        migrations.RunSQL("DELETE FROM django_migrations WHERE app = 'resource_tracker';"),
    ]
