# Generated by Django 3.2.13 on 2023-07-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker_v2', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributedefinition',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list')},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list')},
        ),
        migrations.AlterModelOptions(
            name='resourceattribute',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list')},
        ),
        migrations.AlterModelOptions(
            name='resourcegroup',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list')},
        ),
        migrations.AlterModelOptions(
            name='transformer',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list')},
        ),
    ]
