# Generated by Django 3.2.13 on 2023-06-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker_v2', '0002_alter_attributedefinition_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transformer',
            unique_together={('resource_group', 'attribute_definition'), ('resource_group', 'attribute_definition', 'consume_from_resource_group', 'consume_from_attribute_definition')},
        ),
    ]
