# Generated by Django 3.2.13 on 2023-07-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker_v2', '0003_auto_20230724_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformer',
            name='factor',
            field=models.FloatField(default=1),
        ),
    ]
