kind: Secret
apiVersion: v1
metadata:
  name: "squest-secrets"
  labels:
    app: squest
    service: django
data:
  {% for key, value in squest_django.env_secrets.items() %}
    {{ key }}: "{{ value | b64encode }}"
  {% endfor %}
