# Generated by Django 3.1.7 on 2021-03-18 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spec', models.JSONField(default=dict)),
                ('state', django_fsm.FSMField(default='PENDING', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tower_id', models.IntegerField()),
                ('survey', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], default='CREATE', max_length=10)),
                ('enabled_survey_fields', models.JSONField(default=dict)),
                ('auto_accept', models.BooleanField(default=False)),
                ('auto_process', models.BooleanField(default=False)),
                ('job_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_catalog.jobtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='service_image')),
            ],
        ),
        migrations.CreateModel(
            name='TowerServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=200, unique=True)),
                ('token', models.CharField(max_length=200)),
                ('secure', models.BooleanField(default=True)),
                ('ssl_verify', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_in_survey', models.JSONField(default=dict)),
                ('state', django_fsm.FSMField(default='SUBMITTED', max_length=50)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_catalog.instance')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_catalog.operation')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_catalog.service'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_message', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_catalog.request')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='tower_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_catalog.towerserver'),
        ),
        migrations.AddField(
            model_name='instance',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_catalog.service'),
        ),
        migrations.CreateModel(
            name='UserPermissionOnInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_catalog.instance')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_permission_on_instance',
                'unique_together': {('instance', 'user')},
            },
        ),
    ]
