# Generated by Django 3.1.7 on 2021-04-06 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('state', django_fsm.FSMField(choices=[('OPENED', 'OPENED'), ('CLOSED', 'CLOSED')], default='OPENED', max_length=50)),
                ('date_opened', models.DateField(auto_now=True, null=True)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='service_catalog.instance')),
                ('user_open', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Message',
            new_name='RequestMessage',
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_message', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_catalog.support')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
