# Generated by Django 3.1.7 on 2021-03-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='tower_job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
