# Generated by Django 3.2.11 on 2022-01-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0002_auto_20220120_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='date_available',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
