# Generated by Django 3.1.7 on 2021-05-18 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0002_auto_20210406_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_catalog.instance'),
        ),
        migrations.DeleteModel(
            name='UserPermissionOnInstance',
        ),
    ]
