# Generated by Django 3.1.7 on 2021-03-23 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0002_auto_20210323_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_catalog.instance'),
        ),
        migrations.AlterField(
            model_name='request',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_catalog.operation'),
        ),
    ]
