# Generated by Django 3.2.10 on 2022-01-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0002_instance_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='fill_in_survey',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
