# Generated by Django 3.2.11 on 2022-02-02 15:02

from django.db import migrations, models
from service_catalog.models import Request


def split_fill_in_survey(apps, schema_editor):
    for request in Request.objects.all():
        request.set_fill_in_survey(request.fill_in_survey)


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0002_auto_20220120_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='date_available',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='user_spec',
            field=models.JSONField(blank=True, default=dict, verbose_name='User spec'),
        ),
        migrations.AddField(
            model_name='request',
            name='admin_fill_in_survey',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='instance',
            name='spec',
            field=models.JSONField(blank=True, default=dict, verbose_name='Admin spec'),
        ),
        migrations.AlterField(
            model_name='requestmessage',
            name='content',
            field=models.TextField(default='no content', verbose_name='Message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='content',
            field=models.TextField(default='no content', verbose_name='Message'),
            preserve_default=False,
        ),
        migrations.RunPython(split_fill_in_survey),
    ]
