# Generated by Django 3.2.10 on 2022-01-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0003_auto_20220114_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmessage',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
    ]
