# Generated by Django 3.2.11 on 2022-02-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0004_auto_20220127_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='user_spec',
            field=models.JSONField(blank=True, default=dict, verbose_name='User spec'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='spec',
            field=models.JSONField(blank=True, default=dict, verbose_name='Admin spec'),
        ),
    ]
