# Generated by Django 3.2.10 on 2022-01-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0004_auto_20220117_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='user_open',
            new_name='opened_by',
        ),
    ]
