# Generated by Django 3.1.7 on 2021-03-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0004_auto_20210325_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='process_timeout_second',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='request',
            name='failure_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='periodic_task_date_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
