# Generated by Django 3.1.7 on 2021-07-19 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_catalog', '0004_auto_20210715_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user_set', models.ManyToManyField(blank=True, help_text='The users in this billing group.', related_name='billing_groups', related_query_name='billing_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
