# Generated by Django 3.2.12 on 2022-02-21 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0004_auto_20220217_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalhook',
            name='service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_catalog.service'),
        ),
    ]
