# Generated by Django 3.1.7 on 2021-03-22 10:51

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import service_catalog.models.instance
import service_catalog.models.request


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('service_catalog', '0004_auto_20210319_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='state',
            field=django_fsm.FSMField(default=service_catalog.models.instance.InstanceState['PENDING'], max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='periodic_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask'),
        ),
        migrations.AlterField(
            model_name='request',
            name='state',
            field=django_fsm.FSMField(default=service_catalog.models.request.RequestState['SUBMITTED'], max_length=50),
        ),
    ]
