# Generated by Django 3.2.12 on 2022-04-04 12:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0004_auto_20220228_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestmessage',
            old_name='date_message',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='supportmessage',
            old_name='date_message',
            new_name='creation_date',
        ),
        migrations.AddField(
            model_name='globalhook',
            name='operation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_catalog.operation'),
        ),
        migrations.AddField(
            model_name='operation',
            name='enabled',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='requestmessage',
            name='last_update_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='last_update_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
