# Generated by Django 3.2.12 on 2022-02-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0005_globalhook_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='auto_accept',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='operation',
            name='auto_process',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='enabled',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
