# Generated by Django 3.1.7 on 2021-03-22 11:32

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0005_auto_20210322_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='state',
            field=django_fsm.FSMField(choices=[('SUBMITTED', 'SUBMITTED'), ('NEED_INFO', 'NEED_INFO'), ('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED'), ('CANCELED', 'CANCELED'), ('PROCESSING', 'PROCESSING'), ('COMPLETE', 'COMPLETE'), ('FAILED', 'FAILED')], default='SUBMITTED', max_length=50, protected=True),
        ),
    ]
