# Generated by Django 3.1.7 on 2021-07-21 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('service_catalog', '0005_billinggroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='billing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', related_query_name='instance', to='profiles.billinggroup'),
        ),
        migrations.AlterField(
            model_name='support',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supports', related_query_name='support', to='service_catalog.instance'),
        ),
        migrations.DeleteModel(
            name='BillingGroup',
        ),
    ]
