# Generated by Django 3.1.7 on 2021-07-22 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0005_billinggroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supports', related_query_name='support', to='service_catalog.instance'),
        ),
    ]
