# Generated by Django 3.1.7 on 2021-03-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0006_instance_request_userpermissiononinstance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='survey',
            new_name='enabled_survey_fields',
        ),
    ]
