# Generated by Django 3.2.12 on 2022-07-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0006_auto_20220630_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='external_support_url',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
