# Generated by Django 3.1.7 on 2021-07-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0007_globalhook_servicestatehook'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalhook',
            name='extra_vars',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='servicestatehook',
            name='extra_vars',
            field=models.JSONField(default=dict),
        ),
    ]
