# Generated by Django 3.2.12 on 2022-06-08 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0007_auto_20220607_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmessage',
            name='support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', related_query_name='message', to='service_catalog.support'),
        ),
    ]
