# Generated by Django 3.1.7 on 2021-03-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0007_auto_20210315_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='name',
        ),
    ]
