# Generated by Django 3.2.13 on 2022-07-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0007_service_external_support_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='extra_vars',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='service',
            name='extra_vars',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='towerserver',
            name='extra_vars',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
