# Generated by Django 3.2.13 on 2022-07-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0007_service_external_support_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquestSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode_enabled', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='extra_vars',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='operation',
            name='is_admin_operation',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='extra_vars',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='towerserver',
            name='extra_vars',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
