# Generated by Django 3.2.13 on 2022-07-29 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0008_auto_20220718_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='when',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_catalog.doc', verbose_name='Description documentation'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_catalog.doc', verbose_name='Description documentation'),
        ),
        migrations.CreateModel(
            name='CustomLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=2000)),
                ('button_class', models.CharField(choices=[('default ', 'Default'), ('primary ', 'Blue'), ('secondary', 'Gray'), ('success ', 'Green'), ('danger ', 'Red'), ('warning ', 'Yellow'), ('info ', 'Cyan'), ('light ', 'Light'), ('dark ', 'Dark'), ('link ', 'Link')], default='default ', max_length=30, verbose_name='Button color')),
                ('when', models.CharField(blank=True, max_length=2000, null=True)),
                ('is_admin_only', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('loop', models.CharField(blank=True, max_length=2000)),
                ('services', models.ManyToManyField(blank=True, help_text='Services linked to this custom link.', related_name='custom_links', related_query_name='custom_link', to='service_catalog.Service')),
            ],
        ),
    ]
