# Generated by Django 3.1.7 on 2021-08-05 09:04

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0008_auto_20210728_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', martor.models.MartorField()),
                ('services', models.ManyToManyField(blank=True, help_text='Services linked to this doc.', related_name='docs', related_query_name='doc', to='service_catalog.Service')),
            ],
        ),
    ]
