# Generated by Django 3.1.7 on 2021-03-16 13:10

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0009_request_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='state',
            field=django_fsm.FSMField(default='PENDING', max_length=50),
        ),
    ]
