# Generated by Django 3.2.13 on 2022-07-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0009_squestsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='is_admin_operation',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
