# Generated by Django 3.2.13 on 2022-08-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0009_auto_20220729_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
