# Generated by Django 3.2.12 on 2022-06-28 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0009_alter_approvalstepstate_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='portfolio_image')),
                ('parent_portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_list', related_query_name='portfolio_list', to='service_catalog.portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='parent_portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_list', related_query_name='service_list', to='service_catalog.portfolio'),
        ),
    ]
