# Generated by Django 3.2.12 on 2022-06-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0010_auto_20220628_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalworkflow',
            options={},
        ),
    ]
