# Generated by Django 3.1.7 on 2021-03-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0010_instance_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='auto_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='auto_process',
            field=models.BooleanField(default=False),
        ),
    ]
