# Generated by Django 3.1.7 on 2021-08-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0010_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='ask_variables_on_launch',
            field=models.BooleanField(default=False, help_text='Please enable ask_variables_on_launch on your job_templates'),
        ),
    ]
