# Generated by Django 3.1.7 on 2021-03-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0011_auto_20210316_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='name',
            field=models.CharField(default='my instance test', max_length=100),
            preserve_default=False,
        ),
    ]
