# Generated by Django 3.2.13 on 2023-06-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0012_auto_20221004_1808'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approvalstepstate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='approvalstepstate',
            name='approval_step',
        ),
        migrations.RemoveField(
            model_name='approvalstepstate',
            name='request',
        ),
        migrations.RemoveField(
            model_name='approvalstepstate',
            name='team',
        ),
        migrations.RemoveField(
            model_name='approvalstepstate',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='approvalworkflow',
            name='entry_point',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='approval_workflow',
        ),
        migrations.RemoveField(
            model_name='request',
            name='approval_step',
        ),
        migrations.DeleteModel(
            name='ApprovalStep',
        ),
        migrations.DeleteModel(
            name='ApprovalStepState',
        ),
        migrations.DeleteModel(
            name='ApprovalWorkflow',
        ),
    ]
