# Generated by Django 3.1.7 on 2021-09-14 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_catalog', '0012_auto_20210913_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='spoc',
            field=models.ForeignKey(help_text='Single Point Of Contact', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='SPOC'),
        ),
    ]
