# Generated by Django 3.2.13 on 2023-06-02 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker_v2', '0001_initial'),
        ('service_catalog', '0012_auto_20221004_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='towersurveyfield',
            name='attribute_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tower_survey_fields', related_query_name='tower_survey_field', to='resource_tracker_v2.attributedefinition'),
        ),
    ]
