# Generated by Django 3.2.13 on 2023-06-22 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import service_catalog.models.instance


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20230622_1722'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_catalog', '0013_auto_20230622_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='spoc',
        ),
        migrations.RemoveField(
            model_name='service',
            name='billing_group_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='billing_group_is_selectable',
        ),
        migrations.RemoveField(
            model_name='service',
            name='billing_group_is_shown',
        ),
        migrations.RemoveField(
            model_name='service',
            name='billing_groups_are_restricted',
        ),
        migrations.AddField(
            model_name='instance',
            name='requester',
            field=models.ForeignKey(help_text='Initial request', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Requester'),
        ),
        migrations.AddField(
            model_name='instance',
            name='scope',
            field=models.ForeignKey(default=service_catalog.models.instance.get_default_org, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='instances', related_query_name='instance', to='profiles.scope'),
        ),
    ]
