# Generated by Django 3.1.7 on 2021-09-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0013_instance_spoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_submitted',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='date_opened',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
