# Generated by Django 3.2.13 on 2023-07-19 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0016_auto_20230719_1808'),
        ('service_catalog', '0014_auto_20230622_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list'), 'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='credential',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list')},
        ),
        migrations.AlterModelOptions(
            name='customlink',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list'), 'permissions': [('view_admin_customlink', 'Can view admin custom link')]},
        ),
        migrations.AlterModelOptions(
            name='doc',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list')},
        ),
        migrations.AlterModelOptions(
            name='globalhook',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list')},
        ),
        migrations.AlterModelOptions(
            name='instance',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list'), 'permissions': [('request_on_instance', 'Can request a day2 operation on instance'), ('admin_request_on_instance', 'Can request an admin day2 operation on instance'), ('view_admin_spec_instance', 'Can view admin spec on instance'), ('change_admin_spec_instance', 'Can change admin spec on instance')]},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list')},
        ),
        migrations.AlterModelOptions(
            name='jobtemplate',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list')},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list')},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list')},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list'), 'permissions': [('accept_request', 'Can accept request'), ('cancel_request', 'Can cancel request'), ('reject_request', 'Can reject request'), ('archive_request', 'Can archive request'), ('unarchive_request', 'Can unarchive request'), ('resubmit_request', 'Can re-submit request'), ('process_request', 'Can process request'), ('need_info_request', 'Can ask info request')]},
        ),
        migrations.AlterModelOptions(
            name='requestmessage',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list')},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list'), 'permissions': [('request_on_service', 'Can request operation on service'), ('admin_request_on_service', 'Can request an admin operation on service')]},
        ),
        migrations.AlterModelOptions(
            name='support',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list')},
        ),
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list')},
        ),
        migrations.AlterModelOptions(
            name='towerserver',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list'), 'permissions': [('sync_towerserver', 'Can sync Controller')], 'verbose_name': 'controller', 'verbose_name_plural': 'controllers'},
        ),
        migrations.AlterModelOptions(
            name='towersurveyfield',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list')},
        ),
        migrations.AlterField(
            model_name='customlink',
            name='is_admin_only',
            field=models.BooleanField(default=False, help_text='If "is admin only" then permission service_catalog.view_admin_custom_link is required to see it in your instances'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='quota_scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_instances', related_query_name='quota_instance', to='profiles.scope'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='requester',
            field=models.ForeignKey(help_text='Initial requester', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Requester'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='is_admin_operation',
            field=models.BooleanField(blank=True, default=False, help_text='Create operations are protected by "service_catalog.admin_request_on_service", others by "service_catalog.admin_request_on_instance".', verbose_name='Admin operation'),
        ),
        migrations.DeleteModel(
            name='ServiceStateHook',
        ),
    ]
