# Generated by Django 3.1.7 on 2021-09-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0014_date_to_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtemplate',
            old_name='compliant',
            new_name='is_compliant',
        ),
        migrations.AddField(
            model_name='service',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='job_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_catalog.jobtemplate'),
        ),
    ]
