# Generated by Django 3.2.13 on 2023-06-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0014_auto_20230622_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='billing_group',
        ),
    ]
