# Generated by Django 3.2.13 on 2023-07-21 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profiles', '0016_auto_20230719_1808'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_catalog', '0015_auto_20230719_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'permissions': [('can_approve_approvalstep', 'Can approve an approval step')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStepState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10, verbose_name='Approval state')),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('fill_in_survey', models.JSONField(blank=True, default=dict)),
                ('approval_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_step_states', related_query_name='approval_step_state', to='service_catalog.approvalstep')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', related_query_name='approval_workflow', to='service_catalog.operation')),
                ('scopes', models.ManyToManyField(blank=True, related_name='approval_workflows', to='profiles.Scope', verbose_name='Restricted scopes')),
            ],
            options={
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view', 'list'),
            },
        ),
        migrations.AlterModelOptions(
            name='instance',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list'), 'permissions': [('archive_instance', 'Can archive instance'), ('request_on_instance', 'Can request a day2 operation on instance'), ('admin_request_on_instance', 'Can request an admin day2 operation on instance'), ('view_admin_spec_instance', 'Can view admin spec on instance'), ('change_admin_spec_instance', 'Can change admin spec on instance')]},
        ),
        migrations.RenameField(
            model_name='towersurveyfield',
            old_name='enabled',
            new_name='is_customer_field',
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflow_states', related_query_name='approval_workflow_state', to='service_catalog.approvalworkflow')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_approval_workflow_states', related_query_name='current_approval_workflow_state', to='service_catalog.approvalstepstate')),
            ],
            options={
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view', 'list'),
            },
        ),
        migrations.AddField(
            model_name='approvalstepstate',
            name='approval_workflow_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_step_states', related_query_name='approval_step_state', to='service_catalog.approvalworkflowstate'),
        ),
        migrations.AddField(
            model_name='approvalstepstate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_step_states', related_query_name='approval_step_state', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='approval_workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='service_catalog.approvalworkflow'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='editable_fields',
            field=models.ManyToManyField(blank=True, help_text='Fields allowed to be filled', related_name='approval_steps_as_write_field', to='service_catalog.TowerSurveyField'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='next',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='service_catalog.approvalstep'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='permission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='readable_fields',
            field=models.ManyToManyField(blank=True, help_text='Read only field', related_name='approval_steps_as_read_field', to='service_catalog.TowerSurveyField'),
        ),
        migrations.AddField(
            model_name='request',
            name='approval_workflow_state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_catalog.approvalworkflowstate'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalstepstate',
            unique_together={('approval_workflow_state', 'approval_step')},
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('id', 'approval_workflow'), ('name', 'approval_workflow')},
        ),
    ]
