# Generated by Django 3.2.13 on 2023-06-23 14:00

from django.db import migrations, models
import django.db.models.deletion
import service_catalog.models.instance


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_delete_billinggroup'),
        ('service_catalog', '0015_remove_instance_billing_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='quota_scope',
            field=models.ForeignKey(default=service_catalog.models.instance.get_default_org, on_delete=django.db.models.deletion.PROTECT, related_name='quota_instances', related_query_name='quota_instance', to='profiles.scope'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='scopes',
            field=models.ManyToManyField(blank=True, related_name='scope_instances', related_query_name='scope_instance', to='profiles.Scope'),
        ),
    ]
