# Generated by Django 3.1.7 on 2021-09-23 17:15

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0016_auto_20210921_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_archived',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_catalog.instance'),
        ),
        migrations.AlterField(
            model_name='request',
            name='state',
            field=django_fsm.FSMField(choices=[('SUBMITTED', 'SUBMITTED'), ('NEED_INFO', 'NEED_INFO'), ('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCEPTED'), ('CANCELED', 'CANCELED'), ('PROCESSING', 'PROCESSING'), ('COMPLETE', 'COMPLETE'), ('FAILED', 'FAILED'), ('ARCHIVED', 'ARCHIVED')], default='SUBMITTED', max_length=50),
        ),
    ]
