# Generated by Django 3.2.13 on 2023-07-31 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20230731_1634'),
        ('service_catalog', '0016_alter_request_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalstep',
            name='permission',
            field=models.ForeignKey(limit_choices_to={'content_type__app_label': 'service_catalog', 'content_type__model': 'approvalstep'}, on_delete=django.db.models.deletion.PROTECT, related_name='previous', to='profiles.permission'),
        ),
    ]
