# Generated by Django 3.2.13 on 2023-08-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0017_auto_20230803_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list'), 'ordering': ['-date_submitted'], 'permissions': [('accept_request', 'Can accept request'), ('cancel_request', 'Can cancel request'), ('reject_request', 'Can reject request'), ('archive_request', 'Can archive request'), ('unarchive_request', 'Can unarchive request'), ('re_submit_request', 'Can re-submit request'), ('process_request', 'Can process request'), ('need_info_request', 'Can ask info request'), ('view_admin_survey', 'Can view admin survey')]},
        ),
        migrations.AlterModelOptions(
            name='support',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list'), 'permissions': [('close_support', 'Can close support'), ('reopen_support', 'Can reopen support')]},
        ),
    ]
