# Generated by Django 3.1.7 on 2021-09-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0017_auto_20210923_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='spec',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
