# Generated by Django 3.2.13 on 2023-08-07 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker_v2', '0005_auto_20230803_1126'),
        ('service_catalog', '0019_auto_20230804_1516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TowerServer',
            new_name='AnsibleController',
        ),
        migrations.RenameModel(
            old_name='TowerSurveyField',
            new_name='SurveyField',
        ),
        migrations.AlterModelOptions(
            name='ansiblecontroller',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list'), 'permissions': [('sync_ansiblecontroller', 'Can sync Ansible controller')]},
        ),
        migrations.RenameField(
            model_name='credential',
            old_name='tower_server',
            new_name='ansible_controller',
        ),
        migrations.RenameField(
            model_name='credential',
            old_name='tower_id',
            new_name='remote_id',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='tower_server',
            new_name='ansible_controller',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='tower_id',
            new_name='remote_id',
        ),
        migrations.RenameField(
            model_name='jobtemplate',
            old_name='tower_server',
            new_name='ansible_controller',
        ),
        migrations.RenameField(
            model_name='jobtemplate',
            old_name='tower_id',
            new_name='remote_id',
        ),
        migrations.RenameField(
            model_name='jobtemplate',
            old_name='tower_job_template_data',
            new_name='remote_job_template_data',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='tower_job_id',
            new_name='remote_job_id',
        ),
        migrations.AlterUniqueTogether(
            name='credential',
            unique_together={('remote_id', 'ansible_controller')},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('remote_id', 'ansible_controller')},
        ),
        migrations.AlterUniqueTogether(
            name='jobtemplate',
            unique_together={('remote_id', 'ansible_controller')},
        ),
        migrations.AlterField(
            model_name='surveyfield',
            name='attribute_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='survey_fields', related_query_name='survey_field',
                                    to='resource_tracker_v2.attributedefinition'),
        ),
        migrations.AlterField(
            model_name='surveyfield',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_fields',
                                    related_query_name='survey_field', to='service_catalog.operation'),
        ),
    ]
