# Generated by Django 3.2.13 on 2023-08-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0019_auto_20230804_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalstep',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list'), 'permissions': [('approve_approvalstep', 'Can approve an approval step')]},
        ),
    ]
