# Generated by Django 3.2.13 on 2023-09-06 13:39

from django.db import migrations



def update_current_pending_instances(apps, schema_editor):
    from service_catalog.models import InstanceState, RequestState
    Instance = apps.get_model('service_catalog', 'Instance')
    for pending_instance in Instance.objects.filter(state=InstanceState.PENDING):
        if pending_instance.request_set.count() == 1:
            request = pending_instance.request_set.first()
            if request.state in [RequestState.REJECTED, RequestState.CANCELED]:
                pending_instance.state = InstanceState.ABORTED
                pending_instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0021_approvalstep_auto_accept_condition'),
    ]

    operations = [
        migrations.RunPython(update_current_pending_instances),
    ]
