# Generated by Django 3.2.13 on 2023-09-12 13:24

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):
    dependencies = [
        ('service_catalog', '0022_auto_20230906_1539'),
    ]

    operations = [

        migrations.RunSQL('UPDATE service_catalog_instance SET state = 1 WHERE state = "PENDING";'),
        migrations.RunSQL('UPDATE service_catalog_instance SET state = 2 WHERE state = "PROVISION_FAILED";'),
        migrations.RunSQL('UPDATE service_catalog_instance SET state = 3 WHERE state = "PROVISIONING";'),
        migrations.RunSQL('UPDATE service_catalog_instance SET state = 4 WHERE state = "UPDATING";'),
        migrations.RunSQL('UPDATE service_catalog_instance SET state = 5 WHERE state = "UPDATE_FAILED";'),
        migrations.RunSQL('UPDATE service_catalog_instance SET state = 6 WHERE state = "DELETING";'),
        migrations.RunSQL('UPDATE service_catalog_instance SET state = 7 WHERE state = "DELETED";'),
        migrations.RunSQL('UPDATE service_catalog_instance SET state = 8 WHERE state = "DELETE_FAILED";'),
        migrations.RunSQL('UPDATE service_catalog_instance SET state = 9 WHERE state = "ARCHIVED";'),
        migrations.RunSQL('UPDATE service_catalog_instance SET state = 10 WHERE state = "AVAILABLE";'),
        migrations.RunSQL('UPDATE service_catalog_instance SET state = 11 WHERE state = "ABORTED";'),
        migrations.AlterField(
            model_name='instance',
            name='state',
            field=django_fsm.FSMIntegerField(
                choices=[(1, 'PENDING'), (2, 'PROVISION_FAILED'), (3, 'PROVISIONING'), (4, 'UPDATING'),
                         (5, 'UPDATE_FAILED'), (6, 'DELETING'), (7, 'DELETED'), (8, 'DELETE_FAILED'), (9, 'ARCHIVED'),
                         (10, 'AVAILABLE'), (11, 'ABORTED')], default=1),
        ),

        migrations.RunSQL('UPDATE service_catalog_request SET state = 1 WHERE state = "SUBMITTED";'),
        migrations.RunSQL('UPDATE service_catalog_request SET state = 2 WHERE state = "NEED_INFO";'),
        migrations.RunSQL('UPDATE service_catalog_request SET state = 3 WHERE state = "REJECTED";'),
        migrations.RunSQL('UPDATE service_catalog_request SET state = 4 WHERE state = "CANCELED";'),
        migrations.RunSQL('UPDATE service_catalog_request SET state = 5 WHERE state = "ACCEPTED";'),
        migrations.RunSQL('UPDATE service_catalog_request SET state = 6 WHERE state = "PROCESSING";'),
        migrations.RunSQL('UPDATE service_catalog_request SET state = 7 WHERE state = "COMPLETE";'),
        migrations.RunSQL('UPDATE service_catalog_request SET state = 8 WHERE state = "FAILED";'),
        migrations.RunSQL('UPDATE service_catalog_request SET state = 9 WHERE state = "ARCHIVED";'),
        migrations.AlterField(
            model_name='request',
            name='state',
            field=django_fsm.FSMIntegerField(
                choices=[(1, 'SUBMITTED'), (2, 'NEED_INFO'), (3, 'REJECTED'), (4, 'CANCELED'), (5, 'ACCEPTED'),
                         (6, 'PROCESSING'), (7, 'COMPLETE'), (8, 'FAILED'), (9, 'ARCHIVED')], default=1),
        ),

        migrations.RunSQL('UPDATE service_catalog_support SET state = 1 WHERE state = "OPENED";'),
        migrations.RunSQL('UPDATE service_catalog_support SET state = 2 WHERE state = "CLOSED";'),
        migrations.AlterField(
            model_name='support',
            name='state',
            field=django_fsm.FSMIntegerField(choices=[(1, 'OPENED'), (2, 'CLOSED')], default=1),
        ),

        migrations.RunSQL('UPDATE service_catalog_approvalstepstate SET state = 1 WHERE state = "PENDING";'),
        migrations.RunSQL('UPDATE service_catalog_approvalstepstate SET state = 2 WHERE state = "APPROVED";'),
        migrations.RunSQL('UPDATE service_catalog_approvalstepstate SET state = 3 WHERE state = "REJECTED";'),
        migrations.AlterField(
            model_name='approvalstepstate',
            name='state',
            field=models.IntegerField(choices=[(1, 'PENDING'), (2, 'APPROVED'), (3, 'REJECTED')], default=1,
                                      verbose_name='Approval state'),
        ),
    ]
