# Generated by Django 3.2.13 on 2023-09-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0024_alter_globalhook_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalstep',
            name='auto_accept_condition',
            field=models.TextField(blank=True, default=None, help_text="Ansible like 'when' with `request` as context. No Jinja brackets needed", null=True),
        ),
    ]
