# Generated by Django 3.2.13 on 2023-09-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0019_alter_quota_options'),
        ('service_catalog', '0026_auto_20230919_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalworkflow',
            name='scopes',
            field=models.ManyToManyField(blank=True,
                                         help_text='This workflow will be triggered for the following scopes. Leave empty to trigger for all scopes',
                                         related_name='approval_workflows', to='profiles.Scope',
                                         verbose_name='Restricted scopes'),
        ),
    ]
