# Generated by Django 4.2.6 on 2023-10-26 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_catalog', '0028_set_last_update_on_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='requester',
            field=models.ForeignKey(help_text='Initial requester', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
