# Generated by Django 4.2.6 on 2023-11-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker_v2', '0005_auto_20230803_1126'),
        ('service_catalog', '0030_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='attribute_definitions',
            field=models.ManyToManyField(blank=True, help_text='List of attributes linked to the service, they could be used on operation fields.', related_name='services', to='resource_tracker_v2.attributedefinition'),
        ),
    ]
