# Generated by Django 4.2.6 on 2023-11-21 19:48

from django.db import migrations, models
def set_enabled_to_all_workflow(apps, schema_editor):
    ApprovalWorkflow = apps.get_model("service_catalog", "ApprovalWorkflow")
    ApprovalWorkflow.objects.all().update(enabled=True)

class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0035_alter_request_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalworkflow',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Set to True to use the workflow'),
        ),
        migrations.RunPython(set_enabled_to_all_workflow)
    ]
