# Generated by Django 4.2.13 on 2024-11-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0042_alter_instance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='when',
            field=models.CharField(blank=True, help_text="Ansible like 'when' with `instance` as context. No Jinja brackets needed. Cannot be set on 'create' type of operation as the instance does not exist yet", max_length=2000, null=True),
        ),
    ]
