# Generated by Django 4.2.6 on 2024-11-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0043_operation_when'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobtemplate',
            unique_together={('name', 'tower_server')},
        ),
    ]
