# Generated by Django 4.2.13 on 2025-05-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0044_alter_operation_options_operation_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc',
            options={'ordering': ['title']},
        ),
    ]
