# Generated by Django 4.2.13 on 2025-05-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0045_alter_doc_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list'), 'ordering': ['title']},
        ),
    ]
