# Generated by Django 4.2.21 on 2025-09-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0046_alter_doc_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerserver',
            name='aap_environment',
            field=models.BooleanField(default=False),
        ),
    ]
