from profiles.views.team import *
from profiles.views.token import *
from profiles.views.profile import *
from profiles.views.request_notification_views import *
from profiles.views.instance_notification_views import *
from profiles.views.organization import *
from profiles.views.scope import *
from profiles.views.user import *
from profiles.views.role import *
from profiles.views.globalpermission import *
from profiles.views.quota import *
from profiles.views.permission import *
