- when: squest_mariadb.enabled
  name: Install MariaDB Helm chart
  kubernetes.core.helm:
    name: mariadb
    release_namespace: "{{ squest_k8s_namespace }}"
    chart_version: "{{ squest_mariadb_chart_version }}"
    chart_ref: "{{ squest_mariadb_chart_ref }}"
    values: "{{ squest_mariadb.helm_values }}"

- when: not squest_mariadb.enabled and squest_db.existing_secret is not defined
  name: Create a secret for mariadb
  kubernetes.core.k8s:
    namespace: "{{ squest_k8s_namespace }}"
    definition:
      kind: Secret
      apiVersion: v1
      metadata:
        name: "mariadb"
        labels:
          app: squest
          service: mariadb
      data:
        mariadb-root-password: "{{ squest_db.root_password | b64encode }}"
        mariadb-password: "{{ squest_db.password | b64encode }}"

- when: squest_phpmyadmin.enabled
  name: Install PHPMyAdmin Helm chart
  kubernetes.core.helm:
    name: phpmyadmin
    release_namespace: "{{ squest_k8s_namespace }}"
    chart_version: "{{ squest_phpmyadmin_chart_version }}"
    chart_ref: "{{ squest_phpmyadmin_chart_ref }}"
    values: "{{ squest_phpmyadmin.helm_values }}"
