- when: squest_redis.enabled
  name: Install Redis Helm chart
  kubernetes.core.helm:
    name: redis
    release_namespace: "{{ squest_k8s_namespace }}"
    chart_version: "{{ squest_redis_chart_version }}"
    chart_ref: "{{ squest_redis_chart_ref }}"
    values: "{{ squest_redis.helm_values }}"

- when: not squest_redis.enabled and squest_redis.existing_secret is not defined
  name: Create a secret for redis
  kubernetes.core.k8s:
    namespace: "{{ squest_k8s_namespace }}"
    definition:
      kind: Secret
      apiVersion: v1
      metadata:
        name: "redis"
        labels:
          app: squest
          service: redis
      data:
        redis-password: "{{ squest_redis_secret.password | b64encode }}"
