- name: Deploy Redis CRD
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig_path }}"
    state: present
    definition: "{{ lookup('file', 'redis.crd.v1.2.4.yml') | from_yaml_all }}"

- name: Wait until CSV installed
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k8s_kubeconfig_path }}"
    api_version: "apiextensions.k8s.io/v1"
    kind: CustomResourceDefinition
    name: "redisfailovers.databases.spotahome.com"
    namespace: "redis-operator"
    wait: yes
    wait_sleep: 10
    wait_timeout: 600
    wait_condition:
      type: Established
      status: "True"

- name: Deploy Redis Operator
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig_path }}"
    state: present
    definition: "{{ lookup('file', 'redis.operator.v1.2.4.yml') | from_yaml_all }}"

- name: Wait until deployment available
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k8s_kubeconfig_path }}"
    api_version: "apps/v1"
    kind: Deployment
    name: "redisoperator"
    namespace: "redis-operator"
    wait: yes
    wait_sleep: 10
    wait_timeout: 600
    wait_condition:
      type: Available
      status: "True"

- name: Deploy Redis stack via CRD
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_kubeconfig_path }}"
    state: present
    definition:
      apiVersion: databases.spotahome.com/v1
      kind: RedisFailover
      metadata:
        name: redisfailover
        namespace: "{{ squest_namespace }}"
      spec:
        sentinel:
          replicas: 3
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 100Mi
        redis:
          replicas: 3
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 400m
              memory: 500Mi

- name: Wait until redis deployment available
  kubernetes.core.k8s_info:
    kubeconfig: "{{ k8s_kubeconfig_path }}"
    api_version: "apps/v1"
    kind: Deployment
    name: "redisoperator"
    namespace: "redis-operator"
    wait: yes
    wait_sleep: 10
    wait_timeout: 600
    wait_condition:
      type: Available
      status: "True"
