- name: Deploy celery worker
  kubernetes.core.k8s:
    apply: true
    namespace: "{{ squest_namespace }}"
    definition: "{{ lookup('template', 'celery.deployment.yaml') | from_yaml }}"
  vars:
    celery_name: "celery-worker"
    celery_cmd_args: "worker"

- name: Deploy celery beat
  kubernetes.core.k8s:
    apply: true
    namespace: "{{ squest_namespace }}"
    definition: "{{ lookup('template', 'celery.deployment.yaml') | from_yaml }}"
  vars:
    celery_name: "celery-beat"
    celery_cmd_args: "beat"

