# Generated by Django 3.1.7 on 2021-06-04 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourcePool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResourcePoolAttributeDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resource_pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributes_definition', related_query_name='attribute_definition', to='resource_tracker.resourcepool')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceGroupAttributeDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('consume_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumers', related_query_name='consumer', to='resource_tracker.resourcepoolattributedefinition')),
                ('produce_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producers', related_query_name='producer', to='resource_tracker.resourcepoolattributedefinition')),
                ('resource_group_definition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributes_definition', related_query_name='attribute_definition', to='resource_tracker.resourcegroup')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField(default=0)),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributes', related_query_name='attribute', to='resource_tracker.resource')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resources', related_query_name='resource', to='resource_tracker.resourcegroup'),
        ),
    ]
