# Generated by Django 3.1.7 on 2021-06-07 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcegroupattributedefinition',
            name='resource_group_definition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attribute_definitions', related_query_name='attribute_definition', to='resource_tracker.resourcegroup'),
        ),
    ]
