# Generated by Django 3.1.7 on 2021-09-29 19:31

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource_tracker', '0001_initial'),
        ('service_catalog', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='service_catalog_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', related_query_name='resource', to='service_catalog.instance'),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcepoolattributedefinition',
            unique_together={('name', 'resource_pool')},
        ),
        migrations.AlterUniqueTogether(
            name='resourcegrouptextattributedefinition',
            unique_together={('name', 'resource_group_definition')},
        ),
        migrations.AlterUniqueTogether(
            name='resourcegroupattributedefinition',
            unique_together={('name', 'resource_group_definition')},
        ),
    ]
