# Generated by Django 3.1.7 on 2021-07-06 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0003_auto_20210518_1513'),
        ('resource_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='service_catalog_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_catalog_instances', related_query_name='service_catalog_instance', to='service_catalog.instance'),
        ),
    ]
