# Generated by Django 3.2.7 on 2021-10-06 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0002_auto_20210929_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcegroupattributedefinition',
            name='consume_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumers', related_query_name='consumer', to='resource_tracker.resourcepoolattributedefinition'),
        ),
        migrations.AlterField(
            model_name='resourcegroupattributedefinition',
            name='produce_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producers', related_query_name='producer', to='resource_tracker.resourcepoolattributedefinition'),
        ),
        migrations.AlterField(
            model_name='resourcegroupattributedefinition',
            name='resource_group_definition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_definitions', related_query_name='attribute_definition', to='resource_tracker.resourcegroup'),
        ),
        migrations.AlterField(
            model_name='resourcegrouptextattributedefinition',
            name='resource_group_definition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_attribute_definitions', related_query_name='text_attribute_definition', to='resource_tracker.resourcegroup'),
        ),
    ]
