# Generated by Django 3.1.7 on 2021-06-08 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0002_auto_20210607_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', related_query_name='resource', to='resource_tracker.resourcegroup'),
        ),
        migrations.AlterField(
            model_name='resourceattribute',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', related_query_name='attribute', to='resource_tracker.resource'),
        ),
    ]
