# Generated by Django 3.1.7 on 2021-07-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0008_auto_20210728_1314'),
        ('resource_tracker', '0002_auto_20210721_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='service_catalog_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', related_query_name='resource', to='service_catalog.instance'),
        ),
    ]
