# Generated by Django 3.1.7 on 2021-06-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0003_auto_20210608_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcegroupattributedefinition',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='resourcegroupattributedefinition',
            unique_together={('name', 'resource_group_definition')},
        ),
    ]
