# Generated by Django 3.2.7 on 2021-10-13 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0003_auto_20211006_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepoolattributedefinition',
            name='resource_pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_definitions', related_query_name='attribute_definition', to='resource_tracker.resourcepool'),
        ),
    ]
