# Generated by Django 3.2.7 on 2021-10-15 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0004_alter_resourcepoolattributedefinition_resource_pool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcegroupattributedefinition',
            old_name='resource_group_definition',
            new_name='resource_group',
        ),
        migrations.RenameField(
            model_name='resourcegrouptextattributedefinition',
            old_name='resource_group_definition',
            new_name='resource_group',
        ),
        migrations.AlterUniqueTogether(
            name='resourcegroupattributedefinition',
            unique_together={('name', 'resource_group')},
        ),
        migrations.AlterUniqueTogether(
            name='resourcegrouptextattributedefinition',
            unique_together={('name', 'resource_group')},
        ),
    ]
