# Generated by Django 3.1.7 on 2021-06-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0004_auto_20210624_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepool',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
