# Generated by Django 3.1.7 on 2021-08-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0005_resourcegrouptextattributedefinition_resourcetextattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcegroupattributedefinition',
            name='help_text',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resourcegrouptextattributedefinition',
            name='help_text',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
