# Generated by Django 3.1.7 on 2021-06-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0005_auto_20210624_1520'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourcepoolattributedefinition',
            unique_together={('name', 'resource_pool')},
        ),
    ]
