# Generated by Django 3.2.10 on 2022-01-20 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0002_auto_20220120_1538'),
        ('resource_tracker', '0007_alter_resource_resource_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_deleted_on_instance_deletion',
            field=models.BooleanField(default=True, verbose_name='Delete this resource on instance deletion'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='service_catalog_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', related_query_name='resource', to='service_catalog.instance'),
        ),
    ]
