# Generated by Django 3.2.13 on 2023-05-03 07:28

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0012_auto_20221004_1808'),
        ('taggit', '0005_auto_20220424_2025'),
        ('resource_tracker', '0010_auto_20220804_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='service_catalog_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_v1', related_query_name='resource_v1', to='service_catalog.instance'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='resource_v1', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='resourcegroup',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='resource_group_v1', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='resourcepool',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='resource_pool_v1', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
