# Generated by Django 3.1.7 on 2021-08-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tracker', '0003_auto_20210728_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcepoolattributedefinition',
            name='over_commitment_consumers',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='resourcepoolattributedefinition',
            name='over_commitment_producers',
            field=models.FloatField(default=1),
        ),
    ]
